### ISSUE TITLE
Doc: ImageMagick `loader`, unclear how to specify input and output files!

### ISSUE THREAD

**Issue by nimmolo** [janko/image_processing#121] opened 2024-05-05 21:25 UTC
Sorry, i'm a newbie but I'm pretty sure the docs are unintentionally unclear here. 

In the `ImageProcessing::MiniMagick` `loader` [section](https://github.com/janko/image_processing/blob/master/doc/minimagick.md#loader), you have examples like this:
```ruby
ImageProcessing::MiniMagick.loader(loader: "jpg").call(image)
# convert jpg:input.jpg -auto-orient output.jpg
```
I'm expecting to be able to specify 
- the source `input.jpg` filename, and 
- the output `output.jpg` filename

when calling loader, as implied in the comment. I don't see any parameter but `image`, and that's usually the output filename?

What am I missing?

**Comment by janko** [comment] 2024-05-06 07:11
The [general usage](https://github.com/janko/image_processing?tab=readme-ov-file#usage) section in the readme shows how the source and destination filenames work in both processing backends. The `loader` API is only for specifying some additional input options, so I don't see a reason to repeat how input/output API works, and I wanted the examples to focus on how `loader` is used.

I will close this, as it's not a bug report.

**Closed by janko** 2024-05-06 07:11 UTC

**Comment by nimmolo** [comment] 2024-05-06 19:07
Thanks for the pointer, @janko. I didn't spot that despite several re-reads, but then again i had the flu. 
Sorry for the bother in "issues".
