### ISSUE TITLE
how to add a watermark?

### ISSUE THREAD

**Issue by uurcank** [janko/image_processing#91] opened 2021-08-21 10:40 UTC
I am running into issues when adding an image watermark. 

Adding a text works
`   <%= image_tag @image.variant(gravity: "center", pointsize: "30", fill: "#999", draw: "text 0,0 'Watermark test'").processed.url    %>`

Adding an image does not
     `   <%= image_tag @image.variant(gravity: "center", draw: "image over 0,0 0,0 'watermark.png'").processed.url  %>`
     
 

What would be the correct syntax for this?

**Comment by janko** [comment] 2021-08-21 17:37
What is the error that you get when trying to add an image watermark?

**Comment by uurcank** [comment] 2021-08-22 10:43
Here is what I get  
![image-4-png-1845×406-](https://user-images.githubusercontent.com/6050683/130352263-0c26f0c3-e0ad-4658-b1b4-91e316ba5b45.jpg)

**Comment by uurcank** [comment] 2021-08-22 10:48
`convert-im6.q16: non-conforming drawing primitive definition `image Over 0,0 0,0`

**Comment by uurcank** [comment] 2021-08-22 10:50
https://github.com/ImageMagick/ImageMagick/discussions/2033

**Comment by janko** [comment] 2021-09-13 16:19
Since I'm missing a self-contained example that reproduces the problem (without Active Storage), I'm closing the issue for now.

**Closed by janko** 2021-09-13 16:19 UTC
